from enum import Enum
from typing import Optional, Dict, Any
from decimal import Decimal
from pydantic import BaseModel

class TradeDirection(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"

class TradeCandidate(BaseModel):
    """
    An objective trade proposal generated by a Strategy.
    """
    strategy_name: str
    strategy_version: str
    symbol: str
    direction: TradeDirection
    entry_price: Decimal
    stop_loss: Decimal
    take_profit: Optional[Decimal] = None
    confidence: float = 100.0
    market_conditions: Dict[str, Any]

class RuleFailure(BaseModel):
    rule: str
    status: str = "FAILED"
    reason: str

class StrategyResult(BaseModel):
    """
    The outcome of a strategy evaluating a MarketSnapshot.
    Contains either a valid TradeCandidate or a reason for rejection.
    """
    is_valid: bool
    candidate: Optional[TradeCandidate] = None
    
    # Progress and Diagnostics
    total_rules: int = 0
    passed_rules: list[str] = []
    failed_rule: Optional[RuleFailure] = None
    
    @property
    def setup_progress(self) -> float:
        if self.total_rules == 0:
            return 0.0
        return (len(self.passed_rules) / self.total_rules) * 100.0
        
    @property
    def rejection_reason(self) -> Optional[str]:
        if self.failed_rule:
            return f"{self.failed_rule.rule}: {self.failed_rule.reason}"
        return None
