"""
Aegis Trading System - Paper Trading Validation Models
"""

from decimal import Decimal
from enum import Enum
from pydantic import BaseModel, Field


class PaperTradingStatus(str, Enum):
    ACTIVE = "ACTIVE"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    FAILED_VALIDATION = "FAILED_VALIDATION"
    USER_APPROVED = "USER_APPROVED"


class ValidationReport(BaseModel):
    """
    Generated by the Paper Trading Monitor. 
    Summarizes performance and execution metrics for a specific strategy during its paper trading period.
    """
    strategy_name: str
    status: PaperTradingStatus
    days_running: int
    
    # Performance
    total_trades: int
    win_rate: float
    profit_factor: float
    average_r: float
    maximum_drawdown: float
    net_profit: Decimal
    
    # Execution Quality
    rejected_orders: int = 0
    risk_violations: int = 0
    execution_errors: int = 0
    total_slippage_paid: Decimal = Decimal("0")
    total_commissions_paid: Decimal = Decimal("0")
    
    # Market Behavior
    trending_trades: int = 0
    ranging_trades: int = 0
    breakout_trades: int = 0
    capitulation_trades: int = 0
    
    recommendation: str
