from enum import Enum
from typing import Optional, Dict, Any
from decimal import Decimal
from pydantic import BaseModel

class TradeDirection(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"

class TradeCandidate(BaseModel):
    """
    An objective trade proposal generated by a Strategy.
    """
    strategy_name: str
    strategy_version: str
    symbol: str
    direction: TradeDirection
    entry_price: Decimal
    stop_loss: Decimal
    take_profit: Optional[Decimal] = None
    market_conditions: Dict[str, Any]

class StrategyResult(BaseModel):
    """
    The outcome of a strategy evaluating a MarketSnapshot.
    Contains either a valid TradeCandidate or a reason for rejection.
    """
    is_valid: bool
    candidate: Optional[TradeCandidate] = None
    rejection_reason: Optional[str] = None
