"""
Aegis Trading System — Alembic Environment Configuration

Responsibility:
    - Read the database URL from the application config (app.core.config).
    - Import Base.metadata so Alembic can auto-generate migrations.
    - Run migrations in both online and offline modes.

Architecture rule:
    The database URL is NEVER hardcoded in alembic.ini.
    It always comes from the ATS configuration system (DATABASE_URL env var).
    This ensures the same config that runs the application runs the migrations.
"""

from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

# ── Import ATS config system ──────────────────────────────────────────
# These imports assume alembic is run from the backend/ directory
# where app/ is available in sys.path.
from app.core.config import get_settings
from app.database.base import Base

# ── Alembic Config object ─────────────────────────────────────────────
config = context.config

# ── Logging ───────────────────────────────────────────────────────────
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# ── Load DATABASE_URL from application config ─────────────────────────
# Do NOT hardcode the URL. Use the same config the app uses.
settings = get_settings()
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

# ── Target metadata for autogenerate ──────────────────────────────────
# As new models are created (Phase 2+), they must import from Base
# to be discoverable here. If a model is not imported before Alembic runs,
# its table will not appear in autogenerated migrations.
#
# Future import pattern (Phase 2):
#   import app.models.candle        # noqa: F401 — registers Candle with Base
#   import app.models.instrument    # noqa: F401
#   import app.models.signal        # noqa: F401
#   ... etc
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode.

    Configures the context with just a URL and not an Engine.
    No database connection is required — outputs SQL to stdout.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """
    Run migrations in 'online' mode.

    Creates an Engine from the config and associates a connection
    with the migration context. Requires a live database connection.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()