"""
Migration: Initial Schema — All 18 ENUM types and 15 tables

Revision ID: 001_initial_schema
Revises: None
Create Date: 2026-07-10

Description:
    Creates the complete Aegis Trading System schema as defined in
    04_Database_Design.md. This is a hand-written migration (not autogenerated)
    to ensure exact control over ENUM creation order and table dependency order.

    Creates (in order):
        18 PostgreSQL ENUM types
         6 standalone tables (no FK dependencies)
         9 FK-dependent tables (in dependency order)
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = "001_initial_schema"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ── Upgrade ────────────────────────────────────────────────────────────────


def upgrade() -> None:
    """Apply the initial schema migration."""

    # ═══════════════════════════════════════════════════════════════════════════
    # Step 1: Create all 18 PostgreSQL ENUM types
    # ═══════════════════════════════════════════════════════════════════════════

    op.execute(
        "CREATE TYPE account_type AS ENUM ('PAPER', 'DEMO', 'LIVE')"
    )
    op.execute(
        "CREATE TYPE asset_class AS ENUM ('INDEX', 'FOREX', 'COMMODITY', 'CRYPTO', 'STOCK')"
    )
    op.execute(
        "CREATE TYPE decision_outcome AS ENUM ('PENDING', 'SUCCESS', 'FAILURE', 'EXPIRED')"
    )
    op.execute(
        "CREATE TYPE decision_type AS ENUM ('ENTRY', 'EXIT', 'PARTIAL_EXIT', 'RE_ENTRY', 'REJECT', 'CANCEL')"
    )
    op.execute(
        "CREATE TYPE direction AS ENUM ('LONG', 'SHORT')"
    )
    op.execute(
        "CREATE TYPE indicator_type AS ENUM ('ATR', 'EMA', 'MACD', 'RSI', 'CISD', 'MOMENTUM')"
    )
    op.execute(
        "CREATE TYPE log_level AS ENUM ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')"
    )
    op.execute(
        "CREATE TYPE market_bias AS ENUM ('BULLISH', 'BEARISH', 'NEUTRAL')"
    )
    op.execute(
        "CREATE TYPE order_status AS ENUM ('PENDING', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED', 'REJECTED')"
    )
    op.execute(
        "CREATE TYPE order_type AS ENUM ('MARKET', 'LIMIT', 'STOP')"
    )
    op.execute(
        "CREATE TYPE position_status AS ENUM ('OPEN', 'CLOSED', 'PARTIALLY_CLOSED')"
    )
    op.execute(
        "CREATE TYPE risk_check_type AS ENUM ('POSITION_SIZE', 'STOP_LOSS_DISTANCE', 'EXPOSURE_LIMIT', 'MAX_DRAWDOWN', 'MAX_POSITIONS', 'DAILY_LOSS_LIMIT')"
    )
    op.execute(
        "CREATE TYPE setting_value_type AS ENUM ('STRING', 'INTEGER', 'FLOAT', 'BOOLEAN', 'JSON')"
    )
    op.execute(
        "CREATE TYPE signal_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'EXECUTED', 'EXPIRED', 'CANCELLED')"
    )
    op.execute(
        "CREATE TYPE signal_type AS ENUM ('ENTRY', 'EXIT', 'PARTIAL_EXIT', 'RE_ENTRY')"
    )
    op.execute(
        "CREATE TYPE timeframe AS ENUM ('M1', 'M5', 'M15', 'H1', 'H4')"
    )
    op.execute(
        "CREATE TYPE trade_type AS ENUM ('ENTRY', 'EXIT', 'PARTIAL_EXIT', 'RE_ENTRY')"
    )
    op.execute(
        "CREATE TYPE trend_health AS ENUM ('HEALTHY', 'WEAK', 'BROKEN')"
    )

    # ═══════════════════════════════════════════════════════════════════════════
    # Step 2: Create standalone tables (no FK dependencies)
    # ═══════════════════════════════════════════════════════════════════════════

    # 2.1 instruments — root table, referenced by nearly every other table
    op.create_table(
        "instruments",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("symbol", sa.String(50), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column(
            "asset_class",
            postgresql.ENUM(
                "INDEX", "FOREX", "COMMODITY", "CRYPTO", "STOCK",
                name="asset_class", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("exchange", sa.String(50), nullable=False),
        sa.Column("tick_size", sa.Numeric(18, 8), nullable=False),
        sa.Column(
            "contract_size",
            sa.Numeric(18, 8),
            nullable=False,
            server_default=sa.text("1.0"),
        ),
        sa.Column("currency", sa.String(10), nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", name="uq_instruments_symbol"),
    )
    op.create_index("ix_instruments_asset_class", "instruments", ["asset_class"])
    op.create_index("ix_instruments_exchange", "instruments", ["exchange"])

    # 2.2 accounts — trading accounts
    op.create_table(
        "accounts",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("broker_name", sa.String(100), nullable=False),
        sa.Column("account_number", sa.String(100), nullable=False),
        sa.Column(
            "account_type",
            postgresql.ENUM(
                "PAPER", "DEMO", "LIVE",
                name="account_type", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(10), nullable=False),
        sa.Column(
            "balance",
            sa.Numeric(18, 2),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "is_default",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "broker_name", "account_number",
            name="uq_accounts_broker_account_number",
        ),
    )
    op.create_index("ix_accounts_account_type", "accounts", ["account_type"])
    op.create_index("ix_accounts_is_active", "accounts", ["is_active"])

    # 2.3 market_sessions
    op.create_table(
        "market_sessions",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("exchange", sa.String(50), nullable=False),
        sa.Column("day_of_week", sa.SmallInteger(), nullable=False),
        sa.Column("open_time", sa.Time(), nullable=False),
        sa.Column("close_time", sa.Time(), nullable=False),
        sa.Column("timezone", sa.String(50), nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "exchange", "day_of_week",
            name="uq_market_sessions_exchange_day",
        ),
    )
    op.create_index("ix_market_sessions_exchange", "market_sessions", ["exchange"])

    # 2.4 market_holidays
    op.create_table(
        "market_holidays",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("exchange", sa.String(50), nullable=False),
        sa.Column("holiday_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column(
            "is_full_day",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
        sa.Column("early_close_time", sa.Time(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "exchange", "holiday_date",
            name="uq_market_holidays_exchange_date",
        ),
    )
    op.create_index("ix_market_holidays_exchange", "market_holidays", ["exchange"])
    op.create_index("ix_market_holidays_holiday_date", "market_holidays", ["holiday_date"])

    # 2.5 settings
    op.create_table(
        "settings",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("key", sa.String(100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "value_type",
            postgresql.ENUM(
                "STRING", "INTEGER", "FLOAT", "BOOLEAN", "JSON",
                name="setting_value_type", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_settings_key"),
    )
    op.create_index("ix_settings_category", "settings", ["category"])

    # 2.6 system_logs
    op.create_table(
        "system_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column(
            "level",
            postgresql.ENUM(
                "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL",
                name="log_level", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("module", sa.String(100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_system_logs_level", "system_logs", ["level"])
    op.create_index("ix_system_logs_module", "system_logs", ["module"])
    op.create_index("ix_system_logs_created_at", "system_logs", ["created_at"])

    # ═══════════════════════════════════════════════════════════════════════════
    # Step 3: Create FK-dependent tables (dependency order)
    # ═══════════════════════════════════════════════════════════════════════════

    # 3.1 candles — FK → instruments
    op.create_table(
        "candles",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column(
            "instrument_id",
            sa.BigInteger(),
            sa.ForeignKey("instruments.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(18, 8), nullable=False),
        sa.Column("high", sa.Numeric(18, 8), nullable=False),
        sa.Column("low", sa.Numeric(18, 8), nullable=False),
        sa.Column("close", sa.Numeric(18, 8), nullable=False),
        sa.Column(
            "volume",
            sa.Numeric(20, 8),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "instrument_id", "timestamp",
            name="uq_candles_instrument_timestamp",
        ),
    )
    op.create_index("ix_candles_instrument_id", "candles", ["instrument_id"])
    op.create_index(
        "ix_candles_instrument_timestamp",
        "candles",
        ["instrument_id", "timestamp"],
    )

    # 3.2 indicator_values — FK → instruments, candles
    op.create_table(
        "indicator_values",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column(
            "instrument_id",
            sa.BigInteger(),
            sa.ForeignKey("instruments.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "candle_id",
            sa.BigInteger(),
            sa.ForeignKey("candles.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "indicator_type",
            postgresql.ENUM(
                "ATR", "EMA", "MACD", "RSI", "CISD", "MOMENTUM",
                name="indicator_type", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "timeframe",
            postgresql.ENUM(
                "M1", "M5", "M15", "H1", "H4",
                name="timeframe", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Numeric(18, 8), nullable=False),
        sa.Column("metadata", postgresql.JSONB(), nullable=True),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "instrument_id", "candle_id", "indicator_type", "timeframe",
            name="uq_indicator_values_instrument_candle_type_tf",
        ),
    )
    op.create_index("ix_indicator_values_instrument_id", "indicator_values", ["instrument_id"])
    op.create_index("ix_indicator_values_candle_id", "indicator_values", ["candle_id"])
    op.create_index("ix_indicator_values_indicator_type", "indicator_values", ["indicator_type"])

    # 3.3 market_analysis — FK → instruments
    op.create_table(
        "market_analysis",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column(
            "instrument_id",
            sa.BigInteger(),
            sa.ForeignKey("instruments.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "timeframe",
            postgresql.ENUM(
                "M1", "M5", "M15", "H1", "H4",
                name="timeframe", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("analysis_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "bias",
            postgresql.ENUM(
                "BULLISH", "BEARISH", "NEUTRAL",
                name="market_bias", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "trend_health",
            postgresql.ENUM(
                "HEALTHY", "WEAK", "BROKEN",
                name="trend_health", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence_score", sa.Numeric(5, 2), nullable=False),
        sa.Column("metadata", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "instrument_id", "timeframe", "analysis_timestamp",
            name="uq_market_analysis_instrument_tf_timestamp",
        ),
    )
    op.create_index("ix_market_analysis_instrument_id", "market_analysis", ["instrument_id"])
    op.create_index(
        "ix_market_analysis_instrument_tf_timestamp",
        "market_analysis",
        ["instrument_id", "timeframe", "analysis_timestamp"],
    )

    # 3.4 signals — FK → instruments
    op.create_table(
        "signals",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column(
            "instrument_id",
            sa.BigInteger(),
            sa.ForeignKey("instruments.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "direction",
            postgresql.ENUM("LONG", "SHORT", name="direction", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "signal_type",
            postgresql.ENUM(
                "ENTRY", "EXIT", "PARTIAL_EXIT", "RE_ENTRY",
                name="signal_type", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "timeframe",
            postgresql.ENUM(
                "M1", "M5", "M15", "H1", "H4",
                name="timeframe", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("entry_price", sa.Numeric(18, 8), nullable=True),
        sa.Column("stop_loss", sa.Numeric(18, 8), nullable=True),
        sa.Column("take_profit", sa.Numeric(18, 8), nullable=True),
        sa.Column("confidence_score", sa.Numeric(5, 2), nullable=False),
        sa.Column("strategy_version", sa.String(20), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "APPROVED", "REJECTED", "EXECUTED", "EXPIRED", "CANCELLED",
                name="signal_status", create_type=False,
            ),
            nullable=False,
            server_default="PENDING",
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_signals_instrument_id", "signals", ["instrument_id"])
    op.create_index("ix_signals_status", "signals", ["status"])
    op.create_index("ix_signals_created_at", "signals", ["created_at"])
    op.create_index("ix_signals_expires_at", "signals", ["expires_at"])

    # 3.5 risk_checks — FK → signals
    op.create_table(
        "risk_checks",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column(
            "signal_id",
            sa.BigInteger(),
            sa.ForeignKey("signals.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "check_type",
            postgresql.ENUM(
                "POSITION_SIZE", "STOP_LOSS_DISTANCE", "EXPOSURE_LIMIT",
                "MAX_DRAWDOWN", "MAX_POSITIONS", "DAILY_LOSS_LIMIT",
                name="risk_check_type", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("check_value", sa.Numeric(18, 8), nullable=True),
        sa.Column("threshold_value", sa.Numeric(18, 8), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_risk_checks_signal_id", "risk_checks", ["signal_id"])
    op.create_index("ix_risk_checks_check_type", "risk_checks", ["check_type"])
    op.create_index("ix_risk_checks_passed", "risk_checks", ["passed"])

    # 3.6 orders — FK → signals, instruments, accounts
    op.create_table(
        "orders",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column(
            "signal_id",
            sa.BigInteger(),
            sa.ForeignKey("signals.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column(
            "instrument_id",
            sa.BigInteger(),
            sa.ForeignKey("instruments.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "account_id",
            sa.BigInteger(),
            sa.ForeignKey("accounts.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("client_order_id", sa.String(50), nullable=False),
        sa.Column("broker_order_id", sa.String(100), nullable=True),
        sa.Column(
            "direction",
            postgresql.ENUM("LONG", "SHORT", name="direction", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "order_type",
            postgresql.ENUM(
                "MARKET", "LIMIT", "STOP",
                name="order_type", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(18, 8), nullable=False),
        sa.Column("price", sa.Numeric(18, 8), nullable=True),
        sa.Column("stop_price", sa.Numeric(18, 8), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "FILLED", "PARTIALLY_FILLED", "CANCELLED", "REJECTED",
                name="order_status", create_type=False,
            ),
            nullable=False,
            server_default="PENDING",
        ),
        sa.Column("filled_price", sa.Numeric(18, 8), nullable=True),
        sa.Column("filled_quantity", sa.Numeric(18, 8), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("broker_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_order_id", name="uq_orders_client_order_id"),
    )
    op.create_index("ix_orders_account_id", "orders", ["account_id"])
    op.create_index("ix_orders_signal_id", "orders", ["signal_id"])
    op.create_index("ix_orders_instrument_id", "orders", ["instrument_id"])
    op.create_index("ix_orders_status", "orders", ["status"])
    op.create_index("ix_orders_broker_order_id", "orders", ["broker_order_id"])

    # 3.7 positions — FK → instruments, accounts
    op.create_table(
        "positions",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column(
            "instrument_id",
            sa.BigInteger(),
            sa.ForeignKey("instruments.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "account_id",
            sa.BigInteger(),
            sa.ForeignKey("accounts.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "direction",
            postgresql.ENUM("LONG", "SHORT", name="direction", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "OPEN", "CLOSED", "PARTIALLY_CLOSED",
                name="position_status", create_type=False,
            ),
            nullable=False,
            server_default="OPEN",
        ),
        sa.Column("entry_price", sa.Numeric(18, 8), nullable=False),
        sa.Column("quantity", sa.Numeric(18, 8), nullable=False),
        sa.Column("remaining_quantity", sa.Numeric(18, 8), nullable=False),
        sa.Column("stop_loss", sa.Numeric(18, 8), nullable=True),
        sa.Column("take_profit", sa.Numeric(18, 8), nullable=True),
        sa.Column("unrealized_pnl", sa.Numeric(18, 2), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(18, 2), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_positions_account_id", "positions", ["account_id"])
    op.create_index("ix_positions_instrument_id", "positions", ["instrument_id"])
    op.create_index("ix_positions_status", "positions", ["status"])
    op.create_index("ix_positions_opened_at", "positions", ["opened_at"])

    # 3.8 trades — FK → positions, orders, instruments, accounts
    op.create_table(
        "trades",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column(
            "position_id",
            sa.BigInteger(),
            sa.ForeignKey("positions.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "order_id",
            sa.BigInteger(),
            sa.ForeignKey("orders.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "instrument_id",
            sa.BigInteger(),
            sa.ForeignKey("instruments.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "account_id",
            sa.BigInteger(),
            sa.ForeignKey("accounts.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "direction",
            postgresql.ENUM("LONG", "SHORT", name="direction", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "trade_type",
            postgresql.ENUM(
                "ENTRY", "EXIT", "PARTIAL_EXIT", "RE_ENTRY",
                name="trade_type", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(18, 8), nullable=False),
        sa.Column("price", sa.Numeric(18, 8), nullable=False),
        sa.Column("pnl", sa.Numeric(18, 2), nullable=True),
        sa.Column(
            "commission",
            sa.Numeric(18, 2),
            nullable=True,
            server_default=sa.text("0"),
        ),
        sa.Column("slippage", sa.Numeric(18, 8), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_trades_account_id", "trades", ["account_id"])
    op.create_index("ix_trades_position_id", "trades", ["position_id"])
    op.create_index("ix_trades_order_id", "trades", ["order_id"])
    op.create_index("ix_trades_instrument_id", "trades", ["instrument_id"])
    op.create_index("ix_trades_executed_at", "trades", ["executed_at"])

    # 3.9 decision_logs — FK → signals, instruments
    op.create_table(
        "decision_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column(
            "signal_id",
            sa.BigInteger(),
            sa.ForeignKey("signals.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column(
            "instrument_id",
            sa.BigInteger(),
            sa.ForeignKey("instruments.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "decision_type",
            postgresql.ENUM(
                "ENTRY", "EXIT", "PARTIAL_EXIT", "RE_ENTRY", "REJECT", "CANCEL",
                name="decision_type", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("decision_context", postgresql.JSONB(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("confidence_score", sa.Numeric(5, 2), nullable=False),
        sa.Column("engine_version", sa.String(20), nullable=False),
        sa.Column(
            "outcome",
            postgresql.ENUM(
                "PENDING", "SUCCESS", "FAILURE", "EXPIRED",
                name="decision_outcome", create_type=False,
            ),
            nullable=False,
            server_default="PENDING",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_decision_logs_signal_id", "decision_logs", ["signal_id"])
    op.create_index("ix_decision_logs_instrument_id", "decision_logs", ["instrument_id"])
    op.create_index("ix_decision_logs_decision_type", "decision_logs", ["decision_type"])
    op.create_index("ix_decision_logs_created_at", "decision_logs", ["created_at"])


# ── Downgrade ──────────────────────────────────────────────────────────────


def downgrade() -> None:
    """Reverse the initial schema migration — drop everything in reverse order."""

    # ═══════════════════════════════════════════════════════════════════════════
    # Step 1: Drop FK-dependent tables (reverse creation order)
    # ═══════════════════════════════════════════════════════════════════════════

    op.drop_table("decision_logs")
    op.drop_table("trades")
    op.drop_table("positions")
    op.drop_table("orders")
    op.drop_table("risk_checks")
    op.drop_table("signals")
    op.drop_table("market_analysis")
    op.drop_table("indicator_values")
    op.drop_table("candles")

    # ═══════════════════════════════════════════════════════════════════════════
    # Step 2: Drop standalone tables (reverse creation order)
    # ═══════════════════════════════════════════════════════════════════════════

    op.drop_table("system_logs")
    op.drop_table("settings")
    op.drop_table("market_holidays")
    op.drop_table("market_sessions")
    op.drop_table("accounts")
    op.drop_table("instruments")

    # ═══════════════════════════════════════════════════════════════════════════
    # Step 3: Drop all 18 ENUM types (reverse creation order)
    # ═══════════════════════════════════════════════════════════════════════════

    op.execute("DROP TYPE trend_health")
    op.execute("DROP TYPE trade_type")
    op.execute("DROP TYPE timeframe")
    op.execute("DROP TYPE signal_type")
    op.execute("DROP TYPE signal_status")
    op.execute("DROP TYPE setting_value_type")
    op.execute("DROP TYPE risk_check_type")
    op.execute("DROP TYPE position_status")
    op.execute("DROP TYPE order_type")
    op.execute("DROP TYPE order_status")
    op.execute("DROP TYPE market_bias")
    op.execute("DROP TYPE log_level")
    op.execute("DROP TYPE indicator_type")
    op.execute("DROP TYPE direction")
    op.execute("DROP TYPE decision_type")
    op.execute("DROP TYPE decision_outcome")
    op.execute("DROP TYPE asset_class")
    op.execute("DROP TYPE account_type")