"""Add indicator_state table

Revision ID: 889f0b4867a1
Revises: c3d4e5f6a7b8
Create Date: 2026-07-14 07:35:52.609248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889f0b4867a1'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator_state',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('indicator_name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculation_version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'timeframe', 'indicator_name', name='uq_indicator_state_instrument_tf_name')
    )
    op.create_index('ix_indicator_state_instrument_id', 'indicator_state', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_users_key_prefix'), 'users', ['key_prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_key_prefix'), table_name='users')
    op.drop_index('ix_indicator_state_instrument_id', table_name='indicator_state')
    op.drop_table('indicator_state')
    # ### end Alembic commands ###
