"""add_instrument_status_groups_and_permissions

Revision ID: ec1b29a333af
Revises: 3b0083fb7cc5
Create Date: 2026-07-12 17:32:51.950890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1b29a333af'
down_revision: Union[str, Sequence[str], None] = '3b0083fb7cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_groups',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('instrument_group_association',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['instrument_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'group_id')
    )
    op.execute("CREATE TYPE instrument_status AS ENUM ('ACTIVE', 'WATCHLIST', 'PAUSED', 'DISABLED')")
    op.execute("CREATE TYPE market_type AS ENUM ('US_STOCK', 'CRYPTO', 'FOREX', 'INDEX_CFD', 'COMMODITY')")
    op.add_column('instruments', sa.Column('status', sa.Enum('ACTIVE', 'WATCHLIST', 'PAUSED', 'DISABLED', name='instrument_status'), server_default='ACTIVE', nullable=False))
    op.add_column('instruments', sa.Column('market_type', sa.Enum('US_STOCK', 'CRYPTO', 'FOREX', 'INDEX_CFD', 'COMMODITY', name='market_type'), server_default='US_STOCK', nullable=False))
    op.add_column('instruments', sa.Column('trading_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('instruments', sa.Column('paper_trading_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('instruments', sa.Column('live_trading_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('instruments', sa.Column('allow_new_positions', sa.Boolean(), server_default='true', nullable=False))
    op.drop_column('instruments', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('instruments', 'allow_new_positions')
    op.drop_column('instruments', 'live_trading_enabled')
    op.drop_column('instruments', 'paper_trading_enabled')
    op.drop_column('instruments', 'trading_enabled')
    op.drop_column('instruments', 'market_type')
    op.drop_column('instruments', 'status')
    op.execute("DROP TYPE IF EXISTS instrument_status")
    op.execute("DROP TYPE IF EXISTS market_type")
    op.drop_table('instrument_group_association')
    op.drop_table('instrument_groups')
    # ### end Alembic commands ###
