"""
Model: Signal — Trading signals generated by the Strategy Engine

References:
    04_Database_Design.md — Section 4.7 signals
"""
from datetime import datetime
from decimal import Decimal
from typing import Optional

from sqlalchemy import (
    BigInteger,
    DateTime,
    Enum,
    ForeignKey,
    Identity,
    Index,
    Numeric,
    String,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base
from app.database.enums import Direction, SignalStatus, SignalType, Timeframe


class Signal(Base):
    """Trading signal — output of the decision process before risk checks and execution."""

    __tablename__ = "signals"

    # -- Constraints & Indexes --------------------------------------------------
    __table_args__ = (
        Index("ix_signals_instrument_id", "instrument_id"),
        Index("ix_signals_status", "status"),
        Index("ix_signals_created_at", "created_at"),
        Index("ix_signals_expires_at", "expires_at"),
    )

    # -- Columns ----------------------------------------------------------------
    id: Mapped[int] = mapped_column(BigInteger, Identity(), primary_key=True)

    instrument_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("instruments.id", ondelete="RESTRICT"), nullable=False
    )

    direction: Mapped[Direction] = mapped_column(
        Enum(Direction, name="direction", create_type=False), nullable=False
    )
    signal_type: Mapped[SignalType] = mapped_column(
        Enum(SignalType, name="signal_type", create_type=False), nullable=False
    )
    timeframe: Mapped[Timeframe] = mapped_column(
        Enum(Timeframe, name="timeframe", create_type=False), nullable=False
    )

    entry_price: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 8), nullable=True)
    stop_loss: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 8), nullable=True)
    take_profit: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 8), nullable=True)

    confidence_score: Mapped[Decimal] = mapped_column(Numeric(5, 2), nullable=False)

    strategy_version: Mapped[str] = mapped_column(String(20), nullable=False)

    status: Mapped[SignalStatus] = mapped_column(
        Enum(SignalStatus, name="signal_status", create_type=False),
        nullable=False,
        server_default="PENDING",
    )

    expires_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    metadata_json: Mapped[Optional[dict]] = mapped_column("metadata", JSONB, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # -- Relationships ----------------------------------------------------------
    instrument: Mapped["Instrument"] = relationship(
        "Instrument", back_populates="signals", lazy="selectin"
    )
    risk_checks: Mapped[list["RiskCheck"]] = relationship(
        "RiskCheck", back_populates="signal", lazy="selectin"
    )
    orders: Mapped[list["Order"]] = relationship(
        "Order", back_populates="signal", lazy="selectin"
    )
    decision_logs: Mapped[list["DecisionLog"]] = relationship(
        "DecisionLog", back_populates="signal", lazy="selectin"
    )

    # -- Repr -------------------------------------------------------------------
    def __repr__(self) -> str:
        return (
            f"<Signal(id={self.id}, direction='{self.direction}', "
            f"type='{self.signal_type}', status='{self.status}')>"
        )
